services:
  backend:
    build: ./backend
    working_dir: /app
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"
      - "24678:24678"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    tty: true

volumes:
  backend_node_modules:
  frontend_node_modules:
